name: Explorando el Entorno con Checkout

on:
  push:
    branches:
      - main

jobs:
  exploracion:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo del repositorio (Checkout)
        uses: actions/checkout@v4

      - name: Imprimir un saludo
        run: echo "¡Hola Mundo! Ahora si tenemos el codigo."

      - name: Dime la fecha actual
        run: date

      - name: Muestra el contenido del directorio
        run: ls -la