name: Validacion en Multiples Entornos (Matrix)

on:
  push:
    branches:
      - main

jobs:
  calidad-y-compilacion:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: 1. Descargar el codigo (Checkout)
        uses: actions/checkout@v4

      - name: 2. Configurar entorno de Node.js (Version ${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 3. Instalar dependencias del proyecto
        run: npm install

      - name: 4. Ejecutar control de calidad (Lint)
        run: npm run lint

      - name: 5. Compilar la aplicacion Vue (Build)
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build