name: Instalacion y Build de Vue

on:
  push:
    branches:
      - main

jobs:
  compilacion:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar el codigo (Checkout)
        uses: actions/checkout@v4

      - name: 2. Configurar el entorno de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Instalar dependencias del proyecto
        run: npm install

      - name: 4. Compilar la aplicacion Vue (Build)
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build